[package]
name = "duck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncurses = "5.101.0"
termion = "1.5.6"
unicode-segmentation = "1.9.0"
regex = "1.6.0"
